# Generated by Django 4.2.11 on 2024-03-11 15:42

import calendars.models.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#007bff', max_length=7)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('meeting_duration', models.PositiveIntegerField(default=30)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('finalized', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('submitted', models.BooleanField(default=False)),
                ('member_hash', models.CharField(blank=True, max_length=16, unique=True)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='calendars.calendar')),
            ],
            options={
                'unique_together': {('email', 'calendar')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.calendar')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(validators=[calendars.models.validators.validate_datetime_format])),
                ('preference', models.CharField(choices=[('HIGH', 'High'), ('NO_PREF', 'No Preference'), ('LOW', 'Low')], default='NO_PREF', max_length=7)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.calendar')),
            ],
            options={
                'unique_together': {('calendar', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='MemberTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.member')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.ownertimeslot')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.member')),
                ('suggested_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.schedule')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendars.ownertimeslot')),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='finalized_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_for_calendar', to='calendars.schedule'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to=settings.AUTH_USER_MODEL),
        ),
    ]
