# Generated by Django 5.0.3 on 2024-03-12 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calendars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calendar",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("DAILY", "Daily"),
                    ("WEEKLY", "Weekly"),
                    ("MONTHLY", "Monthly"),
                    ("YEARLY", "Yearly"),
                ],
                default="WEEKLY",
                max_length=7,
            ),
        ),
        migrations.AddField(
            model_name="membertimeslot",
            name="preference",
            field=models.CharField(
                choices=[
                    ("HIGH", "High"),
                    ("NO_PREF", "No Preference"),
                    ("LOW", "Low"),
                ],
                default="NO_PREF",
                max_length=7,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="membertimeslot",
            unique_together={("member", "time_slot")},
        ),
    ]
