# Generated by Django 5.0.3 on 2024-04-09 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("read_status", models.BooleanField(default=False)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            (
                                "added_to_calendar",
                                "for member when they are added to a calendar",
                            ),
                            (
                                "time_updated",
                                "for calendar creator when a member submits/updates their time",
                            ),
                            (
                                "all_times_updated",
                                "for calendar creator when all members have submitted their times",
                            ),
                            (
                                "submit_reminder",
                                "for member when they haven't submitted their time",
                            ),
                            (
                                "calendar_finalized",
                                "for member when the calendar has been finalized",
                            ),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
