# Generated by Django 5.0.3 on 2024-04-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    (
                        "added_to_calendar",
                        "for member when they are added to a calendar",
                    ),
                    (
                        "time_updated",
                        "for calendar creator when a member submits/updates their time",
                    ),
                    (
                        "all_times_updated",
                        "for calendar creator when all members have submitted their times",
                    ),
                    (
                        "submit_reminder",
                        "for member when they haven't submitted their time",
                    ),
                    (
                        "calendar_finalized",
                        "for member when the calendar has been finalized",
                    ),
                    (
                        "removed_from_cal",
                        "for member when they are removed from a calendar",
                    ),
                ],
                max_length=20,
            ),
        ),
    ]
